"""
Django settings for capBackend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import datetime, timedelta
# from dotenv import load_dotenv
import os
import django_on_heroku
import dj_database_url

DATABASE_URL = os.environ.get('DATABASE_URL')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)91p!o&_y1&fx1a@uc^vdk7$f$g#12kpngbf(q5-3v!b95ga%@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['https://capstoners.vercel.app','http://localhost:3000','capstoners-665f8af6ebcf.herokuapp.com','127.0.0.1']


# Application definition


INSTALLED_APPS = [

    
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'auth_app',
    'products',
    'reservations',
    'rest_framework_simplejwt.token_blacklist',
    'analytics',
    'storages',
    
    
]


MIDDLEWARE = [
    
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'capBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


ASGI_APPLICATION = 'capBackend.asgi.application'
WSGI_APPLICATION = 'capBackend.wsgi.application'





# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#somehow nagana kahit di nagamit neto
DATABASES = {
    'default': dj_database_url.config(default=DATABASE_URL)
 }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'cthmDB',
#         'USER': 'root',  #  MySQL username to
#         'PASSWORD': '12345',  #  MySQL password to
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
    
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'cthmDB',
#         'USER': 'admin',
#         'PASSWORD': 'admin',
#         # 'HOST': 'localhost',
#         # 'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'
USE_TZ = True
USE_L10N = True
USE_I18N = True

# USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'frontend/static'),
# ]
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static')
# ]

# MEDIA_URL = '/media/'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=20),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTH_USER_MODEL = 'auth_app.User'




CORS_ORIGIN_ALLOW_ALL = False
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOWED_ORIGINS = [
    'https://capstoners.vercel.app',  # Replace with your frontend domain
    'http://localhost:3000',
    'https://capstoners-665f8af6ebcf.herokuapp.com'  # Add this for local development
]
# para maallow frontend maaccess cookies kase naglologin thru cookies
CORS_ALLOW_CREDENTIALS = True



# Gmail settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dektorsu@gmail.com'
EMAIL_HOST_PASSWORD = 'qovf dpgs lytx kloo'
FRONTEND_URL = 'https://capstoners.vercel.app'
# FRONTEND_URL = 'http://localhost:3000'

# Outlook settings (if you want to use Outlook)
# Uncomment this if you're using Outlook
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_outlook@outlook.com'
# EMAIL_HOST_PASSWORD = 'your_outlook_password'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'dektorsu@gmail.com'
# EMAIL_HOST_PASSWORD = 'qovf dpgs lytx kloo'
# DEFAULT_FROM_EMAIL = 'your-email@example.com'
# ADMIN_EMAIL = 'admin@example.com'  # Add this line

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
    'staticfiles': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
}


django_on_heroku.settings(locals())


AWS_ACCESS_KEY_ID = 'AKIAQ4NXQJTCSQ4WLC6A'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'capstonecthmbucket'
AWS_S3_SIGNATURE_VERSION  = 's3v4'
AWS_S3_REGION_NAME = 'ap-southeast-1'
AWS_S3_VERITY = True
AWS_HEADERS = {
    'Access-Control-Allow-Origin': 'https://capstoners.vercel.app'
}
AWS_DEFAULT_ACL='public-read'
# Additional S3 settings
AWS_QUERYSTRING_AUTH = False  # Makes files public by default
AWS_S3_FILE_OVERWRITE = False  # Ensures files with the same name don't overwrite

# S3FILE_STORAGE_OPTIONS = {
#     'bucket_name': AWS_STORAGE_BUCKET_NAME,
#     'region_name': AWS_S3_REGION_NAME,
#     'access_key': AWS_ACCESS_KEY_ID,
#     'secret_key': AWS_SECRET_ACCESS_KEY,
# }


MEDIA_URL = f'https://capstonecthmbucket.s3.ap-southeast-1.amazonaws.com/products/images/'
MEDIA_ROOT = None