# Generated by Django 5.1 on 2024-09-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='broken_damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
