# Generated by Django 5.1 on 2024-09-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type_id',
        ),
    ]
