# Generated by Django 5.0.6 on 2024-08-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_update', 'Reservation Update'), ('reservation_request', 'Reservation Request'), ('low_stock', 'Low Stock')], max_length=20),
        ),
    ]
