# Generated by Django 5.0.6 on 2024-08-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
    ]
