# Generated by Django 5.1 on 2024-08-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_rename_read_notification_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
