# Generated by Django 5.1 on 2024-09-12 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
