# Generated by Django 5.1 on 2024-09-16 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservation_is_group_reservation_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
