# Generated by Django 5.1 on 2024-10-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_remove_reservation_reserved_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='class_location',
        ),
    ]
