# Generated by Django 5.1 on 2024-10-24 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_remove_classschedule_class_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.classschedule'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_end',
            field=models.DateTimeField(),
        ),
    ]
