# Generated by Django 5.1 on 2024-10-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_reservation_reserved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.classschedule'),
        ),
    ]
