# Generated by Django 5.1 on 2024-09-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservation_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='group_members',
        ),
        migrations.AddField(
            model_name='reservation',
            name='group_members',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
