# Generated by Django 5.1 on 2024-10-10 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_classschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_day',
            field=models.CharField(default='Monday', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='class_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='class_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_end',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
