# Generated by Django 5.1 on 2024-10-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_remove_classschedule_class_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='class_end',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='class_start',
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='class_days',
            field=models.JSONField(default=dict),
        ),
    ]
