# Generated by Django 5.1 on 2024-09-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedorder',
            old_name='order_date',
            new_name='reservation_date',
        ),
        migrations.RenameField(
            model_name='completedorder',
            old_name='order_id',
            new_name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='completedorder',
            name='satisfaction_rate',
        ),
    ]
