# Generated by Django 5.1.2 on 2024-11-06 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_order_date_completedorder_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='completed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
