# Generated by Django 5.0.6 on 2024-07-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
