# Generated by Django 5.0.6 on 2024-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
