# Generated by Django 5.0.6 on 2024-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guest', 'Guest'), ('student', 'Student')], default='guest', max_length=50),
        ),
    ]
