# Generated by Django 5.1 on 2024-10-20 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_user_verification_token_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
