# Generated by Django 5.1 on 2024-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_reservation_reserved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
