# Generated by Django 5.1 on 2024-10-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_remove_reservation_group_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('class_section', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('class_start', models.DateTimeField()),
                ('class_end', models.DateTimeField()),
                ('class_days', models.JSONField(default=list)),
                ('class_location', models.CharField(max_length=100)),
                ('class_instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
