# Generated by Django 5.1 on 2024-10-24 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_remove_classschedule_class_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.classschedule'),
        ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE reservations_reservation ALTER COLUMN reservation_date TYPE timestamp with time zone USING make_timestamp(1970, 1, 1, extract(hour from reservation_date)::int, extract(minute from reservation_date)::int, extract(second from reservation_date)::int)::timestamp with time zone",
                "ALTER TABLE reservations_reservation ALTER COLUMN reservation_date_end TYPE timestamp with time zone USING make_timestamp(1970, 1, 1, extract(hour from reservation_date_end)::int, extract(minute from reservation_date_end)::int, extract(second from reservation_date_end)::int)::timestamp with time zone",
            ],
            reverse_sql=[
                "ALTER TABLE reservations_reservation ALTER COLUMN reservation_date TYPE time USING reservation_date::time",
                "ALTER TABLE reservations_reservation ALTER COLUMN reservation_date_end TYPE time USING reservation_date_end::time",
            ],
        ),
    ]