# Generated by Django 5.1 on 2024-10-10 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_remove_classschedule_class_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_end',
            field=models.DateTimeField(),
        ),
    ]
