# Generated by Django 5.1 on 2024-10-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_reservation_reserved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_end',
            field=models.DateTimeField(),
        ),
    ]
