# Generated by Django 5.1.2 on 2025-01-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_alter_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user_class_section',
            field=models.CharField(default='BIT44', max_length=100),
            preserve_default=False,
        ),
    ]
