# Generated by Django 5.1.2 on 2025-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_reservation_user_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_end',
            field=models.TimeField(),
        ),
    ]
