# Generated by Django 5.1.2 on 2025-01-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_alter_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(),
        ),
    ]
