# Generated by Django 5.1.2 on 2025-01-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_alter_reservation_reserved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_made_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
