# Generated by Django 5.1.2 on 2025-01-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_reservation_reservation_made_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='same_day_reservation',
            field=models.BooleanField(default=False),
        ),
    ]
