# Generated by Django 5.1.2 on 2025-01-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_reservation_same_day_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
