# Generated by Django 5.1.2 on 2025-06-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_reservation_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('quantity_damaged', models.PositiveIntegerField(default=0)),
                ('reservation_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_info', to='reservations.reservationitem')),
            ],
        ),
    ]
