# Generated by Django 5.1 on 2024-10-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_type_alter_producttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.png', max_length=500, upload_to='products/images/'),
        ),
    ]
