# Generated by Django 5.1 on 2024-10-09 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_user_role'),
        ('reservations', '0015_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.classschedule'),
        ),
    ]
