# Generated by Django 5.1 on 2024-10-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_user_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked_out',
            field=models.BooleanField(default=False),
        ),
    ]
