# Generated by Django 5.1.2 on 2025-01-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_user_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_section',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
