# Generated by Django 5.1 on 2024-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_broken_damaged_product_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.CharField(default='type A', max_length=255),
            preserve_default=False,
        ),
    ]
